const ACTION_TYPES = {
  LOGIN_USER_REQUEST: Symbol(),
  LOGIN_USER_SUCCESS: Symbol(),
  LOGIN_USER_ERROR: Symbol(),

  SIGN_UP_USER_REQUEST: Symbol(),
  SIGN_UP_USER_SUCCESS: Symbol(),
  SIGN_UP_USER_ERROR: Symbol(),

};